# Generated by Django 3.0.7 on 2020-07-13 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cv',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
